[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neco-syntax'
on_i = 1

# for ddc
[[plugins]]
repo = 'Shougo/ddc-nextword'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'


[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'tyru/caw.vim'

#colorscheam
[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'oka-h/yozakura.vim'

[[plugins]]
repo = 'jdkanani/vim-material-theme'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'cohama/agit.vim'

[[plugins]]
repo = 'rhysd/committia.vim'

[[plugins]]
repo = 'idanarye/vim-merginal'

